### ISSUE TITLE
MQTT(TypeError: Cannot read property 'forEach' of undefined)

### ISSUE THREAD

**Issue by ubergesundheit** [sensebox/openSenseMap-API#44]
```
TypeError: Cannot read property 'forEach' of undefined
    at outgoing.(anonymous function) (/usr/src/app/node_modules/mqtt/lib/client.js:465:11)
    at that.outgoing.(anonymous function) (/usr/src/app/node_modules/mqtt/lib/client.js:140:15)
    at /usr/src/app/node_modules/mqtt/lib/client.js:881:9
    at Store.del (/usr/src/app/node_modules/mqtt/lib/store.js:77:5)
    at MqttClient._handleAck (/usr/src/app/node_modules/mqtt/lib/client.js:868:26)
    at MqttClient._handlePacket (/usr/src/app/node_modules/mqtt/lib/client.js:293:12)
    at process (/usr/src/app/node_modules/mqtt/lib/client.js:242:12)
    at Writable.writable._write (/usr/src/app/node_modules/mqtt/lib/client.js:252:5)
    at doWrite (/usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:319:64)
    at writeOrBuffer (/usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:308:5)
    at Writable.write (/usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:246:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```

**Comment by ubergesundheit** [comment]
This still isn't resolved :-1:

**Comment by djflex68** [comment]
I have the same problem, is there any workaround available since I really don't unterstand what is causing this ?

**Comment by ubergesundheit** [comment]
The issue didn't occur anymore. The next time it occurs I'll look more into it and update this issue
