### ISSUE TITLE
Error in boxesController.js:366 Can't set headers after they are sent.

### ISSUE THREAD

**Issue by ubergesundheit** [sensebox/openSenseMap-API#60]
```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.format (/usr/src/app/node_modules/restify/lib/response.js:147:10)
    at ServerResponse.send (/usr/src/app/node_modules/restify/lib/response.js:340:14)
    at /usr/src/app/lib/controllers/boxesController.js:366:11
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Comment by ubergesundheit** [comment]
Occurs when the box id is not found
